name: release
# on:
#   push:
#     tags:
#       - "v*"
# jobs:
#   publish:
#     name: publish to crates.io
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       # - name: publish oci-tester to crates.io
#       #   run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: tar.gz zip
          - target: aarch64-apple-darwin
            archive: tar.gz zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
